#!/bin/sh

# Автоматический выход при ошибках.
set -e

# Конфигурация.
WAYLAND_XDG_SHELL_PROTOCOL_FILE="/usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml"
OUTPUT_DIR="src/platform/linux"

# Имена конечных файлов.
XDG_HEADER_FILE=$OUTPUT_DIR/wayland_xdg_protocol.h
XDG_SOURCE_FILE=$OUTPUT_DIR/wayland_xdg_protocol.c
TMP_SOURCE_FILE=$OUTPUT_DIR/wayland_xdg_protocol.tmp

# Проверка существования файла протокола.
if [ ! -f "$WAYLAND_XDG_SHELL_PROTOCOL_FILE" ]; then
    echo "Error: Wayland protocol file not found at $WAYLAND_XDG_SHELL_PROTOCOL_FILE"
    exit 1
fi

# Генерация заголовочного файла если его нет.
if [ ! -f "$XDG_HEADER_FILE" ]; then
    if ! wayland-scanner client-header "$WAYLAND_XDG_SHELL_PROTOCOL_FILE" "$XDG_HEADER_FILE"; then
        echo "Error: Failed to generate header file"
        exit 1
    fi
    echo "Generated header: $XDG_HEADER_FILE"
else
    echo "Header already exists: $XDG_HEADER_FILE"
fi

# Генерация исходного файла если его нет.
if [ ! -f "$XDG_SOURCE_FILE" ]; then
    if ! wayland-scanner private-code "$WAYLAND_XDG_SHELL_PROTOCOL_FILE" "$TMP_SOURCE_FILE"; then
        echo "Error: Failed to generate temporary source file"
        exit 1
    fi

    # Добавление обертки и форматирование.
    (
        echo "// Auto-generated by wayland-scanner"
        echo "// Do not edit manually"
        echo ""
        echo "#include <core/defines.h>"
        echo ""
        echo "#ifdef PLATFORM_LINUX_FLAG"
        # Добавление отступа к сгенерированному коду.
        sed 's/^/    /' "$TMP_SOURCE_FILE"
        echo "#endif"
    ) > "$XDG_SOURCE_FILE"

    # Удаление временного файла.
    rm "$TMP_SOURCE_FILE"

    echo "Generated source: $XDG_SOURCE_FILE"
else
    echo "Source already exists: $XDG_SOURCE_FILE"
fi
